account/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

app_name = 'account'

urlpatterns = [

    url(r'^$', views.view_profile, name='home'),

    url(r'^sign-up/$', views.register_minimal, name='register'),
    url(r'^sign-up-confirmation/$', views.register_confirm, name='register-confirm'),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^profile/$', views.view_profile, name='view-profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit-profile'),

    url(r'^password-change/$', views.password_change, name='password-change'),
    url(r'^password-change/done/$', views.password_change_done, name='password-change-done'),

    url(r'^password-reset/$', views.password_reset, name='password-reset'),
    url(r'^password-reset/done/$', views.password_reset_done, name='password-reset-done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.password_reset_confirm, name='password-reset-confirm'),
    url(r'^reset/done/$', views.password_reset_complete, name='password-reset-complete'),

]

core/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls import handler404, handler500

from .views import custom_handler404, custom_handler500

from homepage import views as homepage_views

urlpatterns = [
    url(r'^$', homepage_views.homepage, name='homepage'),
    #url(r'^errors/404$', custom_handler404, name='error-404'),
    #url(r'^errors/500$', custom_handler500, name='error-500'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^admin/', admin.site.urls),
]

handler404 = custom_handler404
handler500 = custom_handler500

templates/footer.html
<div id="footer">
    <div class="container-fluid">
        <p class="credit">Powered by <a href="https://www.djangoproject.com/">Django</a></p>
    </div>
</div>

templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'homepage' %}">{{ brand_name }}</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li {% if request.get_full_path == homepage_url %} class="active" {% endif %}><a href="{% url 'homepage' %}">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li class="dropdown {% if request.resolver_match.app_name == "account" %}active{% endif %}">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li class="dropdown-header">My profile</li>
                  <li {% if request.get_full_path == account_view_profile_url %}class="active"{% endif %}><a href="{% url 'account:view-profile' %}">view</a></li>
                  <li {% if request.get_full_path == account_edit_profile_url %}class="active"{% endif %}><a href="{% url 'account:edit-profile' %}">edit</a></li>
                  <li role="separator" class="divider"></li>
                  <li {% if request.get_full_path == account_password_change_url %}class="active"{% endif %}><a href="{% url 'account:password-change' %}">change password</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'account:logout' %}">log out</a></li>
              </ul>
            </li>
          {% else %}
              <li {% if request.get_full_path == account_login_url %}class="active"{% endif %}><a href="{% url 'account:login' %}">sign in</a></li>
              <li {% if request.get_full_path == account_register_url %}class="active"{% endif %}><a href="{% url 'account:register' %}">sign up</a></li>
          {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

templates/site-base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    {% block title %}<title>{{ site_title }}</title>{% endblock title%}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/site-base.css' %}" />
    {% block extrahead %}{% endblock extrahead %}
    {% block extrastyle %}{% endblock extrastyle %}
  </head>
  <body>

  <div id="wrap">
      <!-- Static navbar -->

      {% include "navbar.html" %}

      <div class="container-fluid">
          <div class="row">
              <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1" >
              {% block page_content %}
              {% endblock page_content %}
              </div>
          </div>
      </div><!--/.container-fluid -->

      <div id="push"></div>

  </div><!--/.wrap -->

      {% include "footer.html" %}
      
    <script src="{% static 'jquery/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>